### ISSUE TITLE
DisableAllFieldObjects() 

### ISSUE THREAD

**Issue by mmtwr** [rarelysimple/RarelySimple.AvatarScriptLink#1]
**Describe the bug**
I am trying to use DisableAllFieldObjects()  to disable all of the fields on a modeled form, Brief Addiction Monitor.

**To Reproduce**
1. Go to 'Brief Addiction Monitor'
2. Click on 'Edit' with client 1717 in UAT
3. See error preventing form loading:
![image](https://user-images.githubusercontent.com/3520844/83650505-09f90b00-a57e-11ea-84b4-8ae6ebf7a795.png)

**Expected behavior**
I expect that on form load fields will be disabled.  I want only the 'Category' field enabled.

**Screenshots**
In this image you can see the fields are beginning to appear disabled:
![image](https://user-images.githubusercontent.com/3520844/83652007-bc7d9d80-a57f-11ea-9d75-d44abb4b0e05.png)
However, this image shows not all fields are getting disabled, specifically question 11:
![image](https://user-images.githubusercontent.com/3520844/83653068-f4391500-a580-11ea-8fc4-29b1a0141c1b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome (latest)
 - Version 83

**Additional context**
`using NLog;
using RarelySimple.AvatarScriptLink.Objects;
using Rosecrance.ScriptLinkService.Data.Models;
using Rosecrance.ScriptLinkService.Data.Repositories;
using System;
using System.Collections.Generic;
using System.Data.Odbc;

namespace Rosecrance.ScriptLinkService.Web.Commands
{
    public class BAMFormLoadCommand : IRunScriptCommand
    {
        // ***********************************************************************************************
        //  Brief Addiction Monitor BAM FORM load
        //  -------------------------
        //  The form load function will disable all fields except the Category
        // ***********************************************************************************************

        private static readonly Logger logger = LogManager.GetCurrentClassLogger();
        private readonly OptionObject2015 _optionObject2015;
        private readonly IGetDataRepository _repository;

        public BAMFormLoadCommand(OptionObject2015 optionObject2015, IGetDataRepository repository)
        {
            _optionObject2015 = optionObject2015;
            _repository = repository;
        }

        public OptionObject2015 Execute()
        {
            try
            {               
                string dateOfAssessmentFieldNumber = "263.89";
                string categoryFieldNumber = "264.13";
                string methodOfAdministration = "263.92";               
                
                logger.Debug("Method of Administration IsFieldEnabled before: " + _optionObject2015.IsFieldEnabled(methodOfAdministration));
                logger.Debug("Method of Administration IsFieldLocked before: " + _optionObject2015.IsFieldLocked(methodOfAdministration));

                _optionObject2015.SetEnabledField(categoryFieldNumber);
               
                List<string> fields = new List<string>();
                fields.Add(dateOfAssessmentFieldNumber);
                fields.Add("263.90");
                fields.Add(methodOfAdministration);
                fields.Add("263.93");
                fields.Add("263.94");
                fields.Add("263.95");
                fields.Add("263.96");
                fields.Add("263.97");
                fields.Add("263.98");
                fields.Add("263.99");
                fields.Add("264");
                fields.Add("264.01");
                fields.Add("264.02");
                fields.Add("264.03");
                fields.Add("264.04");
                fields.Add("264.05");
                fields.Add("264.06");
                fields.Add("264.07");
                fields.Add("264.08");
                fields.Add("264.09");
                fields.Add("264.10");
                fields.Add("264.11");
                //fields.Add("");
                //fields.Add("");
                _optionObject2015.SetDisabledFields(fields);
                _optionObject2015.DisableAllFieldObjects();
                //_optionObject2015.SetDisabledField("263.89");
                //_optionObject2015.SetDisabledField("263.90"); 
                //_optionObject2015.SetDisabledField(methodOfAdministration);                
            }

            catch (OdbcException ex)
            {
                logger.Error(ex, "An ODBC exception has occurred. See ODBC Data log for more detail.");
                return _optionObject2015.ToReturnOptionObject(ErrorCode.Error, "An ODBC exception has occurred. See the ODBC Data log on the web server for more detail.");
            }
            catch (Exception ex)
            {
                logger.Error(ex, "An unexpected error occurred. Error: {errorMessage}", ex.Message);
                return _optionObject2015.ToReturnOptionObject(ErrorCode.Error, "An unexpected error occurred. Please contact your system administrator. Error: " + ex.Message);
            }

            return _optionObject2015.ToReturnOptionObject();
        }
    }
}`

**Comment by mmtwr** [comment]
Another issue I am having is the behavior based on  whether you choose to either click 'Add' for a new form, or 'Edit' to edit an existing form.  Expected behavior is that if this is a new form to allow all fields to be used, but if you are editing and existing form it should only allow the 'Category'.  Where is it determined whether you are opening new form or editing an existing?

**Comment by scottolsonjr** [comment]
Can you try this code snippet and let me know the following:

- Do you get an error message?
- Do the fields get disabled when you edit an existing submission?

```
    public OptionObject2015 Execute()
    {
        try
        {               
            string dateOfAssessmentFieldNumber = "263.89";
            string categoryFieldNumber = "264.13";
            string methodOfAdministration = "263.92";

            if (_optionObject2015.IsFieldPresent(dateOfAssessmentFieldNumber) && _optionObject2015.GetFieldValue(dateOfAssessmentFieldNumber) != "")
            {
                _optionObject2015.DisableAllFieldObjects();
                _optionObject2015.SetEnabledField(categoryFieldNumber);
            }
        }
        catch (Exception ex)
        {
            logger.Error(ex, "An unexpected error occurred. Error: {errorMessage}", ex.Message);
            return _optionObject2015.ToReturnOptionObject(ErrorCode.Error, "An unexpected error occurred. Please contact your system administrator. Error: " + ex.Message);
        }

        return _optionObject2015.ToReturnOptionObject();
    }
```

**Comment by scottolsonjr** [comment]
I have identified the issue. If myAvatar does not send the Enabled and/or Required properties with the OptionObject then DisableAllFieldObjects() fails.

**Comment by scottolsonjr** [comment]
The fix for this is included in v.1.0.5 on NuGet.

**Comment by mmtwr** [comment]
I updated to new NuGet package, but it still does not disable fields.  Did I need to change anything in code or continue to use the sample you provided?

**Comment by scottolsonjr** [comment]
Can you send the new Verbose log? Also, do all the unit tests pass?

**Comment by mmtwr** [comment]
[radplus_scriptlink_log.pdf](https://github.com/rarelysimple/RarelySimple.AvatarScriptLink/files/4747583/radplus_scriptlink_log.pdf)

**Comment by mmtwr** [comment]
All tests pass.

**Comment by scottolsonjr** [comment]
Ok. So good news, it did try to disable them. It looks like it doesn’t like
having lock null/empty.

I’ll work on the update tonight.

Thanks!

Scott

**Comment by mmtwr** [comment]
Ok sounds good.  If you need me later tonight, I can try to be available.  Just let me know.

**Comment by scottolsonjr** [comment]
Version 1.0.6 includes a fix that ensures Lock it not null when setting a FieldObject as Disabled, Optional, or Required. This also fixes the null Lock value when using DisableAllFieldObjects().

**Comment by mmtwr** [comment]
[radplus_scriptlink_log.pdf](https://github.com/rarelysimple/RarelySimple.AvatarScriptLink/files/4752328/radplus_scriptlink_log.pdf)
Here's the latest log.  There is no error message and the fields do not get disabled.

**Comment by scottolsonjr** [comment]
It looks like we might have found a myAvatar bug or form process that is in conflict with our disable attempt. According the log the OptionObject returns with all of the fields disabled and it passes validation. Here are some items to try to narrow this down.

- Try excluding the field on the second form from the disable.
`_optionObject2015.DisableAllFieldObjects(new List<string>() { "264.75" });`
This may be a special field that shouldn't be touched.
- Try disabling the fields one at a time. Test as you add each fieldObject. I suspect that it will work until you either include all or try to disable a/the problematic field. (If you get cannot find FieldObject, double check your field numbers)
- Check for any Form event logic that may be configured to run on Form Load.
- Check for other ScriptLink calls configured on specific fields.
- Check Guardiant to see if there is any helpful detail recorded there.
