### ISSUE TITLE
Change the FieldObjectBase SetAsDisabled method to not set required to 0

### ISSUE THREAD

**Issue by adrianstovall71** [rarelysimple/RarelySimple.AvatarScriptLink#20]
RarelySimple.AvatarScriptLink/Objects/Advanced/Abstracts/FieldObjectBase.cs has a method called SetAsDisabled.

I can think of a few different scriptlink projects where automatically setting a value for required when changing enabled/disabled would break desired operation of the form (maybe another script was supposed to pull a value and the form shouldn't be submittable without it, but manual entry also shouldn't be allowed.

I would suggest removing the line to unrequire the field.

**Comment by scottolsonjr** [comment]
Great suggestion. I went back and forth on this originally. It would be cleaner and more predictable to remove this behavior.
