### ISSUE TITLE
Don't clear out errorcode or errormessage when using the paramaterless version of ToReturnOptionObject()

### ISSUE THREAD

**Issue by adrianstovall71** [rarelysimple/RarelySimple.AvatarScriptLink#52]
My team has noticed that calling ToReturnOptionObject() clears any values set in errorcode or errormessage.  That may be the intended behavior, but it was definitely unexpected.  I would expect to need to set errorcode 0 or the equivalent enum value to clear those fields.  What do you think about not clearing them unless error code 0 is specified?

**Comment by scottolsonjr** [comment]
You are correct. The default method was envisioned a convenient way to return a successful response with the parameterized override allowing for setting other error codes or messages. I had not considered that the error code and message would have been set prior to this step.

I agree that this assumption is incorrect and that this method should not overwrite the existing values if present. However, something worth considering is whether the ToReturnOptionObject() is still needed in this use case if it has already been configured for return.

The ToReturnOptionObject() method performs the following actions to prepare the OptionObject for return:

1. Clones the OptionObject.
2. Removes unedited rows to trim down the payload and address some errors previously seen in the myAvatar UI in testing.
3. Sets the ErrorCode and ErrorMesg.

I suspect in this use case the method is still valuable for step 2 despite step 3 being handled earlier in the process.

**Comment by adrianstovall71** [comment]
Yes, since the guidance given in training is to return an optionobject
containing only the items you wish to change, I think step 2 is still
important.
